### ISSUE TITLE
memory usage

### ISSUE THREAD

**Issue by billimek** [dniel/traefik-forward-auth0#15]
It's probably not possible due to the nature of being java/spring, but is there any way to otherwise influence how much memory this uses?  It's odd that it would need more than influxdb or prometheus, for example:

![image](https://user-images.githubusercontent.com/6393612/50991792-88659080-14e3-11e9-9873-a164bb58328b.png)

**Comment by dniel** [comment]
It should be possible to get it down to at least 512mb usage. Often SpringBoot2 and Tomcat uses quite alot of memory, and then your custom classes is added on top of that.  Some info about it here https://github.com/wearearima/spring-boot-docker-study

Because the application uses default memory settings right now its quite greedy with allocating memory. 
As the app is using JDK8 it would need JVM opts to restrict the memory usage.

**Comment by dniel** [comment]
I think adding following JVM opts would make the JVM follow the Docker container allocated resources.
```
-XX:+UnlockExperimentalVMOptions
-XX:+UseCGroupMemoryLimitForHeap
-XX:MaxRAMFraction=1
```

**Comment by dniel** [comment]
Check out the code in PR #16, If you have time could you verify that if you add the flags as shown to your deployment it will still run, and use about 500mb of memory after the app has started? Seems to work here on my machine ;) Thanx!

**Comment by dniel** [comment]
alright, seems that the JAVA_OPTS isn't a standard JVM parameter, so I have to update my Dockerfile to pass it through to the java command.

**Comment by billimek** [comment]
@dniel I know this was closed a while back, but thank you for the changes - memory usage is much saner now!

**Comment by dniel** [comment]
Thanx for the feedback!
