### ISSUE TITLE
Implement or document how to perform authorization based on user, group and permission

### ISSUE THREAD

**Issue by dniel** [dniel/traefik-forward-auth0#90]

**Comment by dniel** [comment]
@bigwheels16 Hi! Could you read this page https://github.com/dniel/traefik-forward-auth0/blob/required.scopes/docs/auth0.md to se if it makes any sense? Im thinking about not implementing the authorization in the application but instead implement it by rules in Auth0. What do you think, make sense?

**Comment by bigwheels16** [comment]
Yeah, I'll take a look and let you know.

**Comment by bigwheels16** [comment]
@dniel To start with, I think you got it exactly right in terms of the roles of OAuth, and the purpose of the ID tokens and Access tokens, and who should be consuming each of them.

Regarding the rules in Auth0, I believe that the authorization extension creates a rule that writes the effective permissions to `user.permissions`.  So as long as you make sure your rule comes after the `auth0-authorization-extension` rule, then you should be able to get access to the permissions for that user.

However, as you know, I'm not a fan of writing rules like that in Auth0, since as you point out, Auth0 is the _authorization server_ and the role of the _authorization server_ is simply to issue access tokens, once authentication has happened, and not to make authorization decisions.  As you point out, the _resource server_ is the one who should accept and consume the access tokens and decide whether or not to allow the request based on the contents of the access token.

I do realize you have reasons for doing it this way, one being simplicity.  So I would just call out that this is a deviation from the typical OAuth2 roles, and that for simplicity, the authorization check happens at authentication time, and the implications of that.  The main implication that I can think of is that if they decide to require a different permission for instance, for users that are already authenticated, they will still have access until they are required to authenticate again.

**Comment by dniel** [comment]
@bigwheels16 Thanx for the feedback! 
I agree that its the correct way to implement the authorization code in the resource server, where the application has access to all info from the Access Token and even has the posibility to request more info from Auth0 if needed.  This works perfectly when you have control of the source code of the Resource Server and can implement the logic yourself, or if the Resource Server already has in place a authorization scheme that is compatible with OAuth2. In those cases you dont need the authorization logic in Auth0 or ForwardAuth at all.

The cases where I need to put some simple Authorization logic into Auth0 or ForwardAuth is when you dont have access to the Resource Server code and it isn't compatible with OAuth2.

Some of the reasons why I use rules in Auth0.
- Scopes are available in the Access Token, not in the ID Token.
- ForwardAuth should not use the Access Token.
- Would need custom claims in the ID Token to pass the info to ForwardAuth.
- ID Token should not be used for access control.

The second solution I have thought of is to bend the OAuth2 rules in ForwardAuth and read the scopes in the Access Token and implement a simple required_scopes list per application in the ForwardAuth app.

Both solutions is not optimal and not OAuth2 compliant.
- First one puts authorization logic in the Authorization Server
- Second one read info from Access Token it shouldnt analyze.

Maybe I need to implement both because users like different solutions to the problem, the first one is simple and already in place in Auth0. The seconds need a little bit of development to finish.

**Comment by bigwheels16** [comment]
@dniel I agree with your assessment, generally.  However, consider a different scenario.  Let's say that we have everything configured the same way, except instead of ForwardAuth, we have a different app called AuthzValidator that Traefik forwards all the requests to for validation.  And this app just checks for the existence of a Bearer token in the requests, verifies that the token is valid, and that it has the correct scopes, and if so, allows the request to continue.  And then instead of connecting to this web app via a web browser, you are connecting via an app on your phone, which has a client id and secret.  So in this case, your phone app is the _client_.

In this scenario, AuthzValidator is not performing the _client_ role like ForwardAuth is, instead it's performing the _resource server_ role, or at least assisting in it, even tho ForwardAuth and AuthzValidator are both configured the same way in Traefik.  My point is that the authentication part and authorization part are separate.  Right now ForwardAuth handles the authentication part.  You could also make it handle the authorization part.  I wouldn't consider this breaking the rules.  Instead, I would say that ForwardAuth has two roles: _client_ and _resource server_.  In fact, it's likely that the authentication and authorization pieces would be separate modules within ForwardAuth.

And I don't think that is that weird.  If you were to write a web app with OAuth and didn't put it behind Traefik, and you were going to access it with a browser, and you weren't using a javascript app, then you'd be in the same situation where your web app would be both the _client_ and the _resource server_.  It's the _client_ because your web app is what gets the client id and client secret.  And it's clearly the _resource server_ as well.

Anyway, I'm not saying you should do that.  It would take a bit to code and it would add some complexity to it.  I'm merely suggesting that if you did want to do it, I would still consider that OAuth-compliant.

**Comment by bigwheels16** [comment]
BTW, there is one thing that I am not clear on.  If I am using Traefik and ForwardAuth and I have a web app, how does the web app get access to the Access Token?  I know that Traefik will forward the call to ForwardAuth, which then starts the authorization code grant.  Once that finishes, ForwardAuth will have the access token.  How does ForwardAuth send the access token to the web app?

**Comment by dniel** [comment]
The token is availbale to your application in two ways.
As the Authorization: Bearer <token> http header 

You need to configure Traefik to add the Authorization header to the request after you have authenticated with ForwardAuth you need to to configure which headers Traefik need to add like this https://github.com/dniel/traefik-forward-auth0/blob/master/example/traefik2/traefik2-file.toml#L11-L13 example for Traefik version 2.

Another way is to read the ACCESS_TOKEN cookie which is set, and this is the way ForwardAuth sees that you have user session already and dont need another login at Auth0, it checks if ACCESS_TOKEN is set and use that if set, it will then be set as Authorization http-header.

**Comment by dniel** [comment]
have created new documentation site at readthedocs, which has example of using auth0 rbac, apis, apps and example config for forwardauth to use it.
